### PR TITLE
Complexity task

### PR DESCRIPTION
**Pull request by robframpton**

### CODE REVIEW

**Comment by eduardolundgren** [comment]
Hi @Robert-Frampton, thanks for the contribution this task is very helpful. Is the pull request in the state @mairatma suggested couple of weeks ago?

**Comment by robframpton** [comment]
Hey @eduardolundgren 

It is. This pr provides two tasks, `complexity:report` and `complexity`.

`complexity:report` generates a report in html (the one I showed during the metal training).

`complexity` will just log the maintainability of every file, and report any individual methods that are too complex. The threshold is configurable.

**Comment by eduardolundgren** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by eduardolundgren** [comment]
Running the tests I get:

```
  Complexity Task
Error in plugin 'complexity'
Message:
    2 function(s) are too complicated.
    ✓ should log maintainability of files and complexity of methods
[08:32:22] Logging file maintainability...
Foo.js 92.258
Bar.js 72.635
[08:32:22] Logging method complexity...
Bar.js:4 complexFn is too complicated
    Cyclomatic: 5
    Halstead: 3
      | Effort: 78
      | Volume: 26
      | Vocabulary: 4

    ✓ should break on complex functions
[08:32:22] Report generated at /Users/eduardo/Projects/metal/gulp-metal/test/assets/complexity/artifacts/plato/index.html
    ✓ should generate report based on complexityGlobs
```

**Comment by robframpton** [comment]
Yeah, it's asserting that an error is thrown. I can stub gutil.log if you don't want that output to be seen.

**Comment by eduardolundgren** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by eduardolundgren** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/metal/gulp-metal/compare/146e8ef~1...146e8ef) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by eduardolundgren** [comment]
+ gulp-metal@1.10.0

thanks

**Pull request merged**
