### PR TITLE
Uses prettier for format task instead of esformatter

### LINKED ISSUE #26: Gulp format not behaving as expected
This commit https://github.com/metal/metal.js/commit/b467094b6865f01fc51413cdb54464c699929834 is entirely from the `gulp format` task. There are some strange results from the formatter that we should figure out, specifically indentation issues. See https://github.com/metal/metal.js/commit/b467094b6865f01fc51413cdb54464c699929834#diff-8613848b3fa31f88bb889f2483e95900R937 for reference

### PR DESCRIPTION
**Pull request by jbalsas**
This PR switches from `esformatter` to `prettier` for the `format` task.

This is intended to fix #26, and will opinionatedly configure prettier with:

```
{
    bracketSpacing: false,
    singleQuote: true,
    trailingComma: 'all'
}
```

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @eduardolundgren, I've pushed an update to use `prettier@^1.1.0` instead. For reference, I've executed the `format` task against
- metal.js: https://github.com/metal/metal.js/commit/8791dfbe92069a1f239b58629346f2f0f53248f2
- metal-dropdown: https://github.com/metal/metal-dropdown/commit/d14a38bca6bd66ffa1e9c4dea4252389dc63d380
- senna.js: https://github.com/liferay/senna.js/commit/bbbd7e7d64ad68c99d014bf98635ca2f75ec2b22

**Comment by jbalsas** [comment]
Ok, just need to update the tests that are seemingly asserting that `should call esformatter` 😂

**Comment by jbalsas** [comment]
Tests updated and green! 🎉

**Comment by eduardolundgren** [comment]
Could you remove old esformatter dependencies from package.json before merge? thanks

**Pull request merged**
